// @ts-nocheck
// Event QR-code redemption — server-side validation and reward grant
// ════════════════════════════════════════════════════════════════════════════
// Each event has zero-or-more QR codes pre-generated by the admin team. A QR
// encodes only an opaque `token`; rewards are looked up server-side so the
// client cannot fabricate a reward by editing a token. Each (token, user)
// pair is unique, which prevents a single user from re-scanning the same QR
// (e.g. from a friend's photo).
//
// Required tables (see migrations/v4_qr.sql):
//
//   create table event_qr_codes (
//     id uuid primary key default gen_random_uuid(),
//     event_id uuid references events(id),
//     token text not null unique,
//     reward_type text not null check (reward_type in ('xp','ae','shards','avatar_item','consumable')),
//     reward_value_int int,
//     reward_value_text text,
//     reward_label text,
//     valid_from timestamptz default now(),
//     valid_until timestamptz,
//     max_redemptions int,
//     redeemed_count int default 0,
//     created_by uuid references auth.users(id),
//     created_at timestamptz default now()
//   );
//
//   create table event_qr_redemptions (
//     id uuid primary key default gen_random_uuid(),
//     qr_code_id uuid references event_qr_codes(id),
//     user_id uuid references auth.users(id),
//     redeemed_at timestamptz default now(),
//     unique(qr_code_id, user_id)
//   );
//
//   create or replace function redeem_event_qr(p_token text, p_user_id uuid)
//   returns jsonb language plpgsql security definer as $$
//   declare
//     v_qr event_qr_codes;
//     v_now timestamptz := now();
//   begin
//     select * into v_qr from event_qr_codes where token = p_token for update;
//     if v_qr.id is null then return jsonb_build_object('ok', false, 'error', 'unknown_token'); end if;
//     if v_qr.valid_from > v_now then return jsonb_build_object('ok', false, 'error', 'not_yet_active'); end if;
//     if v_qr.valid_until is not null and v_qr.valid_until < v_now then return jsonb_build_object('ok', false, 'error', 'expired'); end if;
//     if v_qr.max_redemptions is not null and v_qr.redeemed_count >= v_qr.max_redemptions then
//       return jsonb_build_object('ok', false, 'error', 'sold_out');
//     end if;
//     -- Single-use-per-user enforced by the unique constraint below
//     begin
//       insert into event_qr_redemptions(qr_code_id, user_id) values (v_qr.id, p_user_id);
//     exception when unique_violation then
//       return jsonb_build_object('ok', false, 'error', 'already_redeemed');
//     end;
//     update event_qr_codes set redeemed_count = redeemed_count + 1 where id = v_qr.id;
//     -- Apply the reward atomically
//     if v_qr.reward_type = 'xp' then
//       update profiles set xp = coalesce(xp, 0) + v_qr.reward_value_int where user_id = p_user_id;
//     elsif v_qr.reward_type = 'ae' then
//       update profiles set aether = coalesce(aether, 0) + v_qr.reward_value_int where user_id = p_user_id;
//     elsif v_qr.reward_type = 'shards' then
//       update profiles set shards = coalesce(shards, 0) + v_qr.reward_value_int where user_id = p_user_id;
//     elsif v_qr.reward_type = 'avatar_item' or v_qr.reward_type = 'consumable' then
//       insert into user_inventory(user_id, item_id) values (p_user_id, v_qr.reward_value_text)
//         on conflict do nothing;
//     end if;
//     return jsonb_build_object(
//       'ok', true,
//       'reward_type', v_qr.reward_type,
//       'reward_value_int', v_qr.reward_value_int,
//       'reward_value_text', v_qr.reward_value_text,
//       'reward_label', v_qr.reward_label
//     );
//   end $$;
// ════════════════════════════════════════════════════════════════════════════

import { createServerFn } from "@tanstack/react-start";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

export const redeemEventQR = createServerFn({ method: "POST" })
  .inputValidator((input: { userId: string; token: string }) => input)
  .handler(async ({ data }) => {
    const token = (data.token || "").trim();
    if (!token || token.length > 200) return { ok: false, error: "invalid_token" };

    // The Postgres function `redeem_event_qr` performs all validation atomically
    // (token lookup, validity-window check, single-use-per-user enforcement,
    // redemption-cap check, reward grant). See the SQL block at the top of this
    // file for the function body that needs to be deployed.
    const { data: result, error } = await supabaseAdmin.rpc("redeem_event_qr", {
      p_token: token,
      p_user_id: data.userId,
    });

    if (error) {
      console.error("redeem_event_qr RPC failed:", error);
      return { ok: false, error: "rpc_failed", message: error.message };
    }
    return result || { ok: false, error: "no_result" };
  });
